.TH "IB_ACM_RESOLVE_NAME" 3 "2009-09-09" "libibacm" "Libibacm Programmer's Manual" libibacm
.SH NAME
ib_acm_resolve_name \- Resolve path data between the specified names.
.SH SYNOPSIS
.B "#include <infiniband/ib_acm.h>"
.P
.B "int" ib_acm_resolve_name
.BI "(char *" src ","
.BI "char *" dest ","
.BI "struct ib_acm_path_data *" paths ","
.BI "int *" count ","
.BI "struct ib_acm_cm_data *" data ");"
.SH ARGUMENTS
.IP "src" 12
Source system network name or host name.
.IP "dest" 12
Destination system network name or host name.
.IP "paths" 12
On success, returns path record information for the connection.
.IP "count" 12
On success, indicates the number of paths returned.
.IP "data" 12
On success, additional information required for IB CM communication.
.SH "DESCRIPTION"
Discover path information, including identifying the local device,
between the given the source and destination names.
.SH "NOTES"
The source and destination names should match entries in acm_addr.cfg
configuration files on their respective systems.  Typically, the
source and destination names will refer to system host names
assigned to an Infiniband port.  The caller must free the returned
paths array.
.SH "SEE ALSO"
ib_acm_resolve_ip(3), ib_acm_resolve_path(3), ib_acm(7)

