.TH "IB_ACM_RESOLVE_IP" 3 "2009-09-09" "libibacm" "Libibacm Programmer's Manual" libibacm
.SH NAME
ib_acm_resolve_ip \- Resolve path data between the specified addresses.
.SH SYNOPSIS
.B "#include <infiniband/ib_acm.h>"
.P
.B "int" ib_acm_resolve_ip
.BI "(struct sockaddr *" src ","
.BI "struct sockaddr *" dest ","
.BI "struct ib_acm_path_data *" paths ","
.BI "int *" count ","
.BI "struct ib_acm_cm_data *" data ");"
.SH ARGUMENTS
.IP "src" 12
Source address.
.IP "dest" 12
Destination address.
.IP "paths" 12
On success, returns path record information for the connection.
.IP "count" 12
On success, indicates the number of paths returned.
.IP "data" 12
On success, additional information required for IB CM communication.
.SH "DESCRIPTION"
Discover path information, including identifying the local device,
between the given the source and destination addresses.
.SH "NOTES"
The source and destination addresses should match entries in acm_addr.cfg
configuration files on their respective systems.  Typically, the
source and destination addresses will refer to IP addresses assigned
to an IPoIB instance.  The caller must free the returned paths array.
.SH "SEE ALSO"
ib_acm_resolve_name(3), ib_acm_resolve_path(3), ib_acm(7)

