.TH "IBACM" 7 "2012-03-01" "IBACM" "IB ACM User Guide" IBACM
.SH NAME
ibacm \- InfiniBand communication management assistant
.SH SYNOPSIS
.B "#include <infiniband/ib_acm.h>"
.SH "DESCRIPTION"
Used to resolve remote endpoint information before establishing communications
over InfiniBand.
.SH "NOTES"
Th IB ACM provides scalable address and route resolution services over
InfiniBand.  It resolves system network names and IP addresses to InfiniBand
path record data using efficient mechanisms, including caching of data.
.P
The IB ACM provides information needed to establish a connection, but does
not implement the communication management protocol.  It provides services
similar to rdma_getaddrinfo, rdma_resolve_addr, and rdma_resolve_route using
IB multicast.
The IB ACM does not require IPoIB or use standard naming services, such as
DNS, and limits network communication, especially with the IB SA.
The ib_acme utility assists in verifying what options of the ibacm service
may be usable for the current fabric topology.
.P
Client interactions with the ibacm service are done over sockets through
a standard TCP connection.  The librdmacm abstracts this interaction.
.SH "RETURN CODES"
.IP "== 0"
success
.IP "!= 0"
error
.SH "SEE ALSO"
ib_acme(1), ibacm(1)
