.TH IBCHECKNODE 8 "May 21, 2007" "OpenIB" "OpenIB Diagnostics"

.SH NAME
ibchecknode \- validate IB node and report errors 

.SH SYNOPSIS
.B ibchecknode
[\-h] [\-v] [\-N | \-nocolor] [\-G] <lid|guid>

.SH DESCRIPTION
.PP
Check connectivity and do some simple sanity checks for the specified node.
Port address is a lid unless -G option is used to specify a GUID address.

.SH OPTIONS
.PP
\-G      use GUID address argument. In most cases, it is the Port GUID.
        Example:
        "0x08f1040023"
.PP
\-v      increase the verbosity level
.PP
\-N | \-nocolor use mono rather than color mode

.SH EXAMPLE
.PP
ibchecknode 2           # check node via lid 2

.SH SEE ALSO
.BR smpquery(8),
.BR ibaddr(8)

.SH AUTHOR
.TP
Hal Rosenstock
.RI < halr@voltaire.com >
