.TH IBCLEARERRORS 8 "February 1, 2007" "OpenIB" "OpenIB Diagnostics"

.SH NAME
ibclearerrors \- clear error counters in IB subnet

.SH SYNOPSIS
.B ibclearerrors
[\-h] [\-N | \-nocolor] [<topology-file>]

.SH DESCRIPTION
.PP
ibclearerrors is a script which clears the PMA error counters in PortCounters 
by either walking the IB subnet topology or using an already saved topology 
file.

.SH OPTIONS
.PP
\-N | \-nocolor use mono rather than color mode

.SH SEE ALSO
.BR ibnetdiscover(8), perfquery(8)

.SH AUTHOR
.TP
Hal Rosenstock
.RI < halr@voltaire.com >
