.TH IBHOSTS 8 "July 25, 2006" "OpenIB" "OpenIB Diagnostics"

.SH NAME
ibhosts \- show InfiniBand host nodes in topology

.SH SYNOPSIS
.B ibhosts
[\-h] [<topology-file>]

.SH DESCRIPTION
.PP
ibhosts is a script which either walks the IB subnet topology or uses an 
already saved topology file and extracts the CA nodes.

.SH SEE ALSO
.BR ibnetdiscover(8)

.SH AUTHOR
.TP
Hal Rosenstock
.RI < halr@voltaire.com >
