.TH IBLINKINFO 8 "Jan 24, 2008" "OpenIB" "OpenIB Diagnostics"

.SH NAME
iblinkinfo \- report link info for all links in the fabric

.SH SYNOPSIS
.B iblinkinfo
   [-hcdl -C <ca_name> -P <ca_port> -v <lt,hoq,vlstall> -S <guid>
-D <direct_route> \-\-load\-cache <filename>]

.SH DESCRIPTION
.PP
iblinkinfo reports the link info for each port of each switch active in the
IB fabric.

.SH OPTIONS

.PP
.TP
\fB\-S <guid>\fR
Output only the switch specified by <guid> (hex format)
.TP
\fB\-D <direct_route>\fR
Output only the switch specified by the direct route path.
.TP
\fB\-l\fR
Print all information for each link on one line. Default is to print a header
with the switch information and then a list for each port (useful for
grep\'ing output).
.TP
\fB\-d\fR
Print only switches which have a port in the "Down" state.
.TP
\fB\-v <lt,hoq,vlstall>\fR
Verify additional switch settings (<LifeTime>,<HoqLife>,<VLStallCount>)
.TP
\fB\-c\fR
Print port capabilities (enabled and supported values)
.TP
\fB\-C <ca_name>\fR    use the specified ca_name for the search.
.TP
\fB\-P <ca_port>\fR    use the specified ca_port for the search.
.TP
\fB\-R\fR (This option is obsolete and does nothing)
.TP
\fB\-\-load\-cache\fR <filename>
Load and use the cached ibnetdiscover data stored in the specified
filename.  May be useful for outputting and learning about other
fabrics or a previous state of a fabric.  Cannot be used if user
specifies a directo route path.  See
.B ibnetdiscover
for information on caching ibnetdiscover output.
.TP
\fB\-\-diff\fR <filename>
Load cached ibnetdiscover data and do a diff comparison to the current
network or another cache.  A special diff output for iblinkinfo
output will be displayed showing differences between the old and current
fabric links.  See
.B ibnetdiscover
for information on caching ibnetdiscover output.

.SH AUTHOR
.TP
Ira Weiny
.RI < weiny2@llnl.gov >
