.TH IBNODES 8 "July 25, 2006" "OpenIB" "OpenIB Diagnostics"

.SH NAME
ibnodes \- show InfiniBand nodes in topology

.SH SYNOPSIS
.B ibnodes
[<topology-file>]

.SH DESCRIPTION
.PP
ibnodes is a script which either walks the IB subnet topology or uses an 
already saved topology file and extracts the IB nodes (CAs and switches).

.SH SEE ALSO
.BR ibnetdiscover(8)

.SH AUTHOR
.TP
Hal Rosenstock
.RI < halr@voltaire.com >
