.TH IBQUERYERRORS 8 "Oct 30, 2009" "OpenIB" "OpenIB Diagnostics"

.SH NAME
ibqueryerrors.pl \- query and report non-zero IB port counters

.SH SYNOPSIS
.B ibqueryerrors.pl
[-s <err1,err2,...> -c -r -C <ca_name> -P <ca_port> -G <node_guid>
-D <direct_route> -d -k -K]

.SH DESCRIPTION
.PP
ibqueryerrors.pl reports port counters.  This is similar to ibcheckerrors with
the additional ability to filter out selected errors, include the optional
transmit and receive data counters, and report full link information for the
link reported.

.SH OPTIONS

.PP
.TP
\fB\-s <err1,err2,...>\fR
Suppress the errors listed in the comma separated list provided.
.TP
\fB\-c\fR
Suppress some of the common "side effect" counters.  These counters usually do
not indicate an error condition and can be usually be safely ignored.
.TP
\fB\-G <node_guid>\fR
Report results only for the node guid specified.
.TP
\fB\-S <node_guid>\fR
\-S is provided only for backward compatibility and works the same as "-G"
.TP
\fB\-D <direct_route>\fR
Report results only for the switch specified by the direct route path.
.TP
\fB\-r\fR
Report the port information.  This includes LID, port, external port (if
applicable), link speed setting, remote GUID, remote port, remote external port
(if applicable), and remote node description information.
.TP
\fB\-\-data\fR
Include the optional transmit and receive data counters.
.TP
\fB\-\-switch\fR  print data for switches only
.TP
\fB\-\-ca\fR  print data for CA's only
.TP
\fB\-\-router\fR  print data for routers only
.TP
\fB\-\-clear\-errors\fR \fB\-k\fR Clear error counters after read.
\-k and \-K can be used together to clear both errors and counters.
.TP
\fB\-\-clear\-counts\fR \fB\-K\fR Clear data counters after read.
\fBCAUTION\fR clearing data counters will occur regardless of if they are
printed or not.  This is because data counters are only \fBprinted\fR on ports
which have errors.  This means if a port has 0 errors and the \-K option is
specified the data counters will be cleared without any printed output.
.TP
\fB\-\-details\fR include transmit discard details
.TP
\fB\-R\fR  (This option is obsolete and does nothing)

.SH COMMON OPTIONS
.PP
\-d      raise the IB debugging level.
	May be used several times (-ddd or -d -d -d).
.PP
\-e      show send and receive errors (timeouts and others)
.PP
\-h      show the usage message
.PP
\-v      increase the application verbosity level.
	May be used several times (-vv or -v -v -v)
.PP
\-V      show the version info.

# Other common flags:
.PP
\-C <ca_name>    use the specified ca_name.
.PP
\-P <ca_port>    use the specified ca_port.
.PP
\-t <timeout_ms> override the default timeout for the solicited mads.


.SH AUTHOR
.TP
Ira Weiny
.RI < weiny2@llnl.gov >
