.TH IBSWITCHES 8 "July 25, 2006" "OpenIB" "OpenIB Diagnostics"

.SH NAME
ibswitches\- show InfiniBand switch nodes in topology

.SH SYNOPSIS
.B ibswitches
[\-h] [<topology-file>]

.SH DESCRIPTION
.PP
ibswitches is a script which either walks the IB subnet topology or uses an 
already saved topology file and extracts the switch nodes.

.SH SEE ALSO
.BR ibnetdiscover(8)

.SH AUTHOR
.TP
Hal Rosenstock
.RI < halr@voltaire.com >
