.TH "RDMA_DISCONNECT" 3 "2007-05-15" "librdmacm" "Librdmacm Programmer's Manual" librdmacm
.SH NAME
rdma_disconnect \- This function disconnects a connection.
.SH SYNOPSIS
.B "#include <rdma/rdma_cma.h>"
.P
.B "int" rdma_disconnect
.BI "(struct rdma_cm_id *" id ");"
.SH ARGUMENTS
.IP "id" 12
RDMA identifier.
.SH "DESCRIPTION"
Disconnects a connection and transitions any associated QP to the error state.
This routing may be called by both the client and server side of a connection.
.SH "SEE ALSO"
rdma_connect(3), rdma_listen(3), rdma_accept(3)
