.TH "rdma_free_devices" 3 "rdma_free_devices" "May 2007" "Librdmacm Programmer's Manual" librdmacm
.SH NAME
rdma_free_devices \- Frees the list of devices returned by rdma_get_devices.
.SH SYNOPSIS
.B "#include <rdma/rdma_cma.h>"
.P
.B "void" rdma_free_devices
.BI "(struct ibv_context **" list ");"
.SH ARGUMENTS
.IP "list" 12
List of devices returned from rdma_get_devices.
.SH "DESCRIPTION"
Frees the device array returned by rdma_get_devices.
.SH "SEE ALSO"
rdma_get_devices
