.\" -*- nroff -*-
.\"
.TH UMAD_GET_CAS_NAMES 3  "2007-03-12" "OpenIB" "OpenIB Programmer's Manual"
.SH "NAME"
umad_get_cas_names \- get list of available InfiniBand devices
.SH "SYNOPSIS"
.nf
.B #include <infiniband/umad.h>
.sp
.BI "int umad_get_cas_names(char " "cas[][UMAD_CA_NAME_LEN]" ", int " "max" );
.fi
.SH "DESCRIPTION"
.B umad_get_cas_names()
fill the first
.I max
(or the available devices if available in host less than this number) in the array
.I cas.
The argument
.I cas
is a character array with
.I max
entries, each with
.B UMAD_CA_NAME_LEN
characters.
.SH "RETURN VALUE"
.B umad_get_cas_names()
returns a non-negative value equal to the number of devices found.
.SH "SEE ALSO"
.BR umad_init (3),
.BR umad_get_ca_portguids (3)

.SH "AUTHORS"
.TP
Dotan Barak <dotanb@mellanox.co.il>
