.\" -*- nroff -*-
.\"
.TH UMAD_DEBUG 3  "May 11, 2007" "OpenIB" "OpenIB Programmer\'s Manual"
.SH "NAME"
umad_debug \- set debug level
.SH "SYNOPSIS"
.nf
.B #include <infiniband/umad.h>
.sp
.BI "int umad_debug(int " "level" );
.fi
.SH "DESCRIPTION"
.B umad_debug()
set the umad library internal debugging level to
.I level\fR.
The following
debugging levels are supported: 0 - no debugging (the default),
1 - basic debugging information, 2 - verbose debugging. Negative values are
ignored. Note that the current debugging level can
be queried by passing negative values.
.SH "RETURN VALUE"
.B umad_debug()
returns the actual verbosity level after updating it (if required).
.SH "AUTHORS"
.TP
Hal Rosenstock <halr@voltaire.com>
.TP
Dotan Barak <dotanb@mellanox.co.il>
