from pyverbs.libibverbs_enums cimport (
    IBV_DEVICE_RAW_SCATTER_FCS,
    IBV_DEVICE_PCI_WRITE_END_PADDING,
    IBV_ADVISE_MR_ADVICE_PREFETCH,
    IBV_ADVISE_MR_ADVICE_PREFETCH_WRITE,
    IBV_ADVISE_MR_FLAG_FLUSH,
    IBV_ADVISE_MR_ADVICE_PREFETCH_NO_FAULT,
    IBV_ALLOCATOR_USE_DEFAULT,
)

from libc.stddef cimport size_t

_IBV_DEVICE_RAW_SCATTER_FCS = IBV_DEVICE_RAW_SCATTER_FCS
_IBV_DEVICE_PCI_WRITE_END_PADDING = IBV_DEVICE_PCI_WRITE_END_PADDING
_IBV_ALLOCATOR_USE_DEFAULT = <size_t>IBV_ALLOCATOR_USE_DEFAULT
_IBV_ADVISE_MR_ADVICE_PREFETCH = IBV_ADVISE_MR_ADVICE_PREFETCH
_IBV_ADVISE_MR_ADVICE_PREFETCH_WRITE = IBV_ADVISE_MR_ADVICE_PREFETCH_WRITE
_IBV_ADVISE_MR_FLAG_FLUSH = IBV_ADVISE_MR_FLAG_FLUSH
_IBV_ADVISE_MR_ADVICE_PREFETCH_NO_FAULT = IBV_ADVISE_MR_ADVICE_PREFETCH_NO_FAULT
