# SPDX-License-Identifier: (GPL-2.0 OR Linux-OpenIB)

#cython: language_level=3


cdef extern from 'infiniband/efadv.h':

    cpdef enum:
        EFADV_DEVICE_ATTR_CAPS_RDMA_READ
        EFADV_DEVICE_ATTR_CAPS_RNR_RETRY
        EFADV_DEVICE_ATTR_CAPS_CQ_WITH_SGID
        EFADV_DEVICE_ATTR_CAPS_RDMA_WRITE
        EFADV_DEVICE_ATTR_CAPS_UNSOLICITED_WRITE_RECV
        EFADV_DEVICE_ATTR_CAPS_CQ_WITH_EXT_MEM_DMABUF
        EFADV_DEVICE_ATTR_CAPS_COMP_CNTR

    cpdef enum:
        EFADV_QP_DRIVER_TYPE_SRD

    cpdef enum:
        EFADV_QP_FLAGS_UNSOLICITED_WRITE_RECV
        EFADV_QP_FLAGS_INLINE_WRITE

    cpdef enum:
        EFADV_WR_EX_WITH_PROCESSING_HINTS

    cpdef enum:
        EFADV_WR_PROCESSING_HINT_BURST_PPS_SENSITIVE

    cpdef enum:
        EFADV_WC_EX_WITH_SGID
        EFADV_WC_EX_WITH_IS_UNSOLICITED

    cpdef enum:
        EFADV_MR_ATTR_VALIDITY_RECV_IC_ID
        EFADV_MR_ATTR_VALIDITY_RDMA_READ_IC_ID
        EFADV_MR_ATTR_VALIDITY_RDMA_RECV_IC_ID

    cpdef enum:
        EFADV_SQ_DEPTH_ATTR_INLINE_WRITE

    cpdef enum:
        EFADV_MEMORY_LOCATION_VA
        EFADV_MEMORY_LOCATION_DMABUF

    cpdef enum:
        EFADV_COMP_CNTR_INIT_WITH_COMP_EXTERNAL_MEM
        EFADV_COMP_CNTR_INIT_WITH_ERR_EXTERNAL_MEM
