#!/bin/bash

inst /etc/modprobe.d/truescale.conf
inst /usr/libexec/truescale-serdes.cmds

# All files needed by truescale-serdes.cmds need to be present here
inst /sbin/lspci
inst /bin/grep
inst /bin/sed
inst /usr/bin/logger
inst /usr/sbin/dmidecode
inst /bin/readlink
inst /bin/echo
