etc/rdma/modules/srp_daemon.conf
etc/srp_daemon.conf
usr/lib/srp_daemon/start_on_all_ports
usr/lib/systemd/system/srp_daemon.service
usr/lib/systemd/system/srp_daemon_port@.service
usr/lib/udev/rules.d/60-srp_daemon.rules
usr/sbin/ibsrpdm
usr/sbin/srp_daemon
usr/share/doc/rdma-core/ibsrpdm.md usr/share/doc/srptools/
usr/share/man/man5/srp_daemon.service.5
usr/share/man/man5/srp_daemon_port@.service.5
usr/share/man/man8/ibsrpdm.8
usr/share/man/man8/srp_daemon.8
