.\" -*- nroff -*-
.\" Copyright (c) 2017 Mellanox Technologies, Inc.
.\" Licensed under the OpenIB.org (MIT) - See COPYING.md
.\"
.TH MLX4DV 7 2017-04-19 1.0.0
.SH "NAME"
mlx4dv \- Direct verbs for mlx4 devices
.br
This is low level access to mlx4 devices to perform data path operations,
without general branching performed by \fBibv_post_send\fR(3).

.SH "DESCRIPTION"
The libibverbs API is an abstract one. It is agnostic to any underlying
provider specific implementation. While this abstraction has the advantage
of user applications portability it has a performance penalty. For some
applications optimizing performance is more important than portability.

The mlx4 direct verbs API is intended for such applications.
It exposes mlx4 specific low level data path (send/receive/completion)
operations, allowing the application to bypass the libibverbs data path API.

This interface consists from one hardware specific header file
with relevant inline functions and conversion logic from ibverbs structures
to mlx4 specific structures.

The direct include of mlx4dv.h together with linkage to mlx4 library will
allow usage of this new interface.

Once an application uses the direct flow the locking scheme is fully managed
by itself. There is an expectation that no mixed flows in the data path for both
direct/non-direct access will be by same application.

.SH "NOTES"
.SH "SEE ALSO"
.BR ibv_post_send (3),
.BR verbs (7)

.SH "AUTHORS"
.TP
Maor Gottlieb <maorg@mellanox.com>
