.\" -*- nroff -*-
.\" Licensed under the OpenIB.org (MIT) - See COPYING.md
.\"
.TH MLX4DV_QUERY_DEVICE 3 2017-06-27 1.0.0
.SH "NAME"
mlx4dv_query_device \- Query device capabilities specific to mlx4
.SH "SYNOPSIS"
.nf
.B #include <infiniband/mlx4dv.h>
.sp
.BI "int mlx4dv_query_device(struct ibv_context *ctx_in,
.BI "                        struct mlx4dv_context *attrs_out);
.fi
.SH "DESCRIPTION"
.B mlx4dv_query_device()
Query mlx4 specific device information that is usable via the direct verbs interface.
.PP
This function returns a version and compatibility mask. The version represents
the format of the internal hardware structures that mlx4dv.h exposes.
Future additions of new fields to the existing structures are handled by
the comp_mask field.
.PP
.nf
struct mlx4dv_context {
.in +8
uint8_t         version;
uint32_t        max_inl_recv_sz; /* Maximum supported size of inline receive  */
uint64_t        comp_mask;
.in -8
};

.fi
.SH "RETURN VALUE"
0 on success or the value of errno on failure (which indicates the failure reason).
.SH "NOTES"
 * Compatibility mask (comp_mask) is an in/out field.
.SH "SEE ALSO"
.BR mlx4dv (7),
.BR ibv_query_device (3)
.SH "AUTHORS"
.TP
Maor Gottlieb <maorg@mellanox.com>
