[Unit]
# Partially support distro network setup scripts that run after
# systemd-modules-load.service but before sysinit.target, eg a classic network
# setup script. Run them after modules have loaded.
Wants=network-pre.target
Before=network-pre.target
